spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatdb?useSSL=false
    username: shyu
    password: 1234
  jpa:
    database: mysql
    #    innoDB
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  #chatServersecretacesstokenchatServersecretacesstokenchatServersecretacesstoken
  secretKey: Y2hhdFNlcnZlcnNlY3JldGFjZXNzdG9rZW5jaGF0U2VydmVyc2VjcmV0YWNlc3N0b2tlbmNoYXRTZXJ2ZXJzZWNyZXRhY2Vzc3Rva2Vu
  expiration: 3000 # 3000분